---
title: "Welcome to our MBTA Project"
Authors: Jen Guo and Mandy Sun
bibliography: reference.bib
format:
    html: 
        code-fold: false
        embed-resources: true
---

## **About Us:**

Jen Guo:

Jen Guo is a grad student in the Data Science and Analytics program at Georgetown University. She is a part-time grad student and work as a full-time analyst. She came from Granville, Ohio. Jen completed her undergrad at Denison University in Ohio with a BA in Data Analytics (concentration in biology) and a Minor in Mathematics. After graduating from undergrad, she worked full-time as an Analyst for a healthcare technology provider company. Jen has gained several technological skills throughout my undergrad and grad program, that includes Python, R, and SQL. In addition, my area of interest in Data Science/ Analytics is the biology/ public health field.

Mandy Sun:

Mandy Sun is currently in Georgetown University pursuing a masters in Data Science and Analytics and an undergraduate degree in computer science in film and media studies. Previous to DSAN, she worked in multiple data roles, including working with the Bureau of Justice Statistics working with criminal justice systems expenditure and employment data, as well as wrangling with Georgetown's student-run coffee shop's sales data. In her free time, she is binging a film or TV-show, attempting a random hobby, or *attempting* recipes as a newly adult.

## Introduction Summary:

The **Massachusetts Bay Transportation Authority (MBTA)** is a public transportation system in the Greater Boston area, Massachusetts. Services includes subway, bus, commuter rail, ferry, and paratransit.

The MBTA is the fourth busiest public-transit system. Thousands of locals heavily rely on the MBTA system daily. The MBTA system is a necessity for Boston and several low-income people and communities rely on it.

### Timeline:

The MBTA history has had several mishaps:

*2000: 5 billion in debt - MBTA was passed on debt from The Big Dig.*

*2019: COVID-19 - MBTA ridership decreased immensely.*

*July 2021: Green line collision 27 injured and sent to hospital.*

*July 2022: Red Train Malfunction - Robert Lalin, 29, dies after arm stuck in the train, dragged him to death*

*July 2022: Orange Line catches fire - Southbound train caught fire after a piece of metal came loose and contacted the electric rails, producing flame.*

*Aug 2022: Bus Catches fire - Fire broke out in Arborway yard, two transit workers sent to hospital for smoke inhalation.*

*September 2022: Green line station, overhead wire falls - Wire falls, causing a spark and a loud bang.*

### Rennovation Program:

Due to the dangers of the MBTA and the public dissatisfaction, The Massachusetts Bay Transportation Authority (MBTA) system began its renovation program in 2022.

The purpose of the project was to build a safer, reliable, and more accessible transportation system.

Project includes updating old infrastructures, stations, tracks, and power systems.

## Problem Statement:

For this DSAN 5000 Final Portfolio Project, we want to analyze if the ongoing renovation project improved the reliability and performance of the MBTA system. Are there early indicators of significant improvement to the usage and performance of the MBTA system?

## Key Focuses:

-   Service Reliability and Ridership Patterns 

-   Future Infrastructure Upgrades

-   Economic Impact

-   Root Causes of Infrastructure Decline 

-   Safety and Environmental Concerns

## **Research Questions:**

1.  Service Reliability and Ridership Patterns

    1.  How does replacing aging MBTA trains affect service reliability and ridership trends?

    2.  Is there an increase in accurate predictions of the MBTA trains arriving on time before and after the start of the renovation program?

2.  Economic Impact

    1.  What pattern can be extracted from the expenses, revenues, and debts from the MBTA system from the years 2019 to 2023?

    2.  Is there a correlation between the reliability of the MBTA system and the expenses spend on the MBTA system through 2019 to 2023?

3.  Future Infrastructure Updates

    1.  What historical patterns in delays and ridership can predict future infrastructure needs?

    2.  Which stations or routes should be prioritized for upgrades to maximize ridership growth and minimize disruptions?

4.  News Trends Regarding the MBTA system

    1.  What is the trend in news medisa regarding the MBTA system? Is there largely dissatisfaction and negative connotation words and feedback from the public regarding the MBTA system?

## Literature Review

1.  "Transforming the T: How MBTA Reform Can Right Our Broken Transportation System" : The MBTA structure needs to be renovated, there is a lack of financial stability, and the transportation system needs to be more reliable and efficient. <cite>\@chieppo2015transforming\<`/cite>`{=html}

    a\. Financial: MBTA has heavy debt. Recommends the MBTA system to outsource bus operations to reduce costs and attempt to save more money.

    b\. Must improve customer experience: Article suggest the MBTA system must improve customer satisfaction and comfort in order to improve ridership and revenue.

    c\. MBTA fare: Suggested to increase fare cost. Attempted to increase revenue while also making sure lower income riders are not at a complete disadvantage.

2.  "MBTA: Privacy, SmartCards, and the MBTA: A Policy Analysis of the MBTA’s New Automated Fare Collection System": Discusses the challenges in collecting fares for the MBTA system.<cite>\@brelinskymbta</cite>

    a\. The MBTA system pivots to using electronic forms of payments for fares to improve convenience for customers and operational efficiency.

    b\. Along with the transition to electronic form of payment, privacy concerns increase. There is concern for tracking customers, hackers, leaked and misused data by third parties. Attempted to collect minimal data on ridership to protect customer data.

3.  "Improving high-frequency transit reliability: a case study of the **MBTA** Green Line through simulation and field experiments of real-time control strategies": Discussed ways to improve the reliability of the MBTA system, and the challenges to achieve this goal. <cite>\@fabian2017improving</cite>

    a\. Improve Ride Reliability: Conducted study on the MBTA Green Line - controls at terminals decreased wait times for rides. Proved that "real-time intervention" can greatly improve ridership satisfaction.

    b\. Challenges: Limitations included poor station infrastructure, inspection, and operator performance.

    c\. Study recommended that improving infrastructure, more training for operators stationed at terminals, and adding more supervision would help improve the reliability of the MBTA system.

4.  "Strategies for meeting future capacity needs on the light rail MBTA Green Line": Discusses the infrastructure improvements needed to improve the MBTA Green Line.<cite>\@sindel2017strategies</cite>

    a\. Challenges for improvement: Best to address the run-down infrastructure of the MBTA Green Line in order to meet ridership capacity and satisfaction.

    b\. Strategy: Analysis on changing schedules increased ride capacity and decreased wait time for passengers. Best to create linear optimization models to analyze performance of MBTA subway rides.

5.  "The Cost of Subway Delays: A Counterfactual Welfare Analysis of Boston’s T": The reliability issues and terrible economic status of the MBTA system are urgent cases that needs to be addressed.<cite>\@dean2022cost</cite>

    a\. Reliability Issue: The MBTA system is unreliable which has economical impact. There is financial loss for common riders due to the delays and unreliability of the MBTA system.

    b\. Old Infrastructure: The aging infrastructure of the MBTA system is a big liability. The COVID-19 pandemic had a huge impact on the progress of addressing the MBTA infrastructure, because the pandemic lowered the number of ridership and revenue. So the renovation program of the MBTA system was further delayed.

6.  "Bus Operation Safety Business Intelligence Solution: Applying Analytics for Key Performance Indicator, Investigation, and Targeted Actions Analyses with a Centralized Data Warehouse": Discusses the application of data analytics to improve the safety and efficiency of the MBTA system. <cite>\@ding2024bus</cite>

    a\. Safety: A Business Intelligence (BI) system was built by the MBTA to improve bus safety by having more data-driven decision making take place. In addition, there needs to be more safety inspections to increase safety of these buses.

    b\. Analytics: MBTA system needs to utilize more application of data analysis like geospatial maps, charts, and data visualization to help with their analysis on improving the system safety and efficiency.