# Summary

This section will focus on the challenges, benchmarks, and conclusions drawn from our exploratory data analysis portion. It provides a technical overview on obstacles and limiations with our EDA. Then, it will provide a brief overview on our next step. 

## Challenges

### EDA Method Difficulties
- Performing EDA required finetuning the cleaning code iteratively 


## Conclusion 

### Primary Thoughts 
- Histograms showed right-skewed distributions for "num_predictions" and "num_accurate_predictions", indicating a smaller frequency of very high prediction values.
- Themes around "speed restrictions", "shutdowns", and "approvals" emerged, highlighting both challenges and improvements in the MBTA system. This is indication of MBTA staying true to their progress in renovation and improving transparency. 
    - Positive sentiment correlated with terms like "approves", "launches", and "improvement", while negative sentiment centered around "shutdown" and "restrictions".
- The logistic regression model, anova models, and majority of t-tests conducted showed no significance. The event of trips made on time happening did not have signigicant relationship between the amounts in the net postion, expenses, revenues, and debts regarding the MBTA system from 2019 to 2023. Only the t-test results of the debts dataset showed potential of a significant relationship, so taking the debts dataset for further analysis in supervised and un-supervised learning would be ideal.
- Data present in alert notifications align with our historical and contextual understanding of the MBTA (i.e. construction rise in 2024 with accidents highest in 2022) 

### Next Steps 
- Following the collection, we will now perform unsupervised learning given the lack of significant relationships from our statistical tests. 

### Potential Improvements
- Further work on this project will involve finetunng the EDA, improving our existing models and reinterpreting our results. 

**[Click here to visit the next step: unsupervised learning](../unsupervised-learning/main.ipynb)**
